### PR TITLE
Added Game Over Screen For Example

### PR DESCRIPTION
**Pull request by tacotacoenchilada**
**Added Game Over Screen For Example**

### CODE REVIEW

**Review by OkiStuff — COMMENTED** [review]
Looks good, im just going to do some general clean up of the code later. I also have some improvements that I can add myself

**Comment by tacotacoenchilada** [comment]
> Looks good, im just going to do some general clean up of the code later. I also have some improvements that I can add myself
Alright

**Comment by OkiStuff** [comment]
this is the worst pr ever ngl

**Comment by tacotacoenchilada** [comment]
> this is the worst pr ever ngl

shut the fuck up

**Comment by tacotacoenchilada** [comment]
poop

**Pull request closed without merging**
